### ISSUE TITLE
Root Directory

### ISSUE THREAD

**Issue by 3ThousandFaces** [zigurous/unity-cc0textures-importer#2]
I am getting a root directory error when attempting an import. It seems to happen at the zip stage, I was not able to find any documentation about how to resolve it.

**Comment by adamgraham** [comment]
> I am getting a root directory error when attempting an import. It seems to happen at the zip stage, I was not able to find any documentation about how to resolve it.

Would you be able to provide the exact error message and stack trace from the Unity console?

**Comment by 3ThousandFaces** [comment]
[CC0TexturesImporter] Cannot find central directory
UnityEngine.Debug:LogError (object,UnityEngine.Object)

Zigurous.Importer.CC0Textures.Log:Error (string) (at Library/PackageCache/com.zigurous.importer.cc0textures@de7ae8b98e/Editor/Log.cs:21)

Zigurous.Importer.CC0Textures.WebClient:UnzipFiles (string,string,string) (at Library/PackageCache/com.zigurous.importer.cc0textures@de7ae8b98e/Editor/WebClient.cs:130)

Zigurous.Importer.CC0Textures.WebClient/<DownloadAsset>d__1:MoveNext () (at Library/PackageCache/com.zigurous.importer.cc0textures@de7ae8b98e/Editor/WebClient.cs:33)

UnityEngine.UnitySynchronizationContext:ExecuteTasks ()

**Comment by 3ThousandFaces** [comment]
Resolved. Issue was only to put the ending name of the link in instead of the full link from the Readme. Thank you!
